set(_CATKIN_CURRENT_PACKAGE "bulb")
set(bulb_VERSION "0.0.0")
set(bulb_MAINTAINER "huzaifa <huzaifa@todo.todo>")
set(bulb_PACKAGE_FORMAT "2")
set(bulb_BUILD_DEPENDS "roscpp" "rospy")
set(bulb_BUILD_EXPORT_DEPENDS "roscpp" "rospy")
set(bulb_BUILDTOOL_DEPENDS "catkin")
set(bulb_BUILDTOOL_EXPORT_DEPENDS )
set(bulb_EXEC_DEPENDS "roscpp" "rospy")
set(bulb_RUN_DEPENDS "roscpp" "rospy")
set(bulb_TEST_DEPENDS )
set(bulb_DOC_DEPENDS )
set(bulb_URL_WEBSITE "")
set(bulb_URL_BUGTRACKER "")
set(bulb_URL_REPOSITORY "")
set(bulb_DEPRECATED "")